import React from "react";
import "./Homepage.css";
import Sharky from "./../../assets/sharky.jpg";
import Trash from "./../../assets/pastic.jpg";
import Sol from "./../../assets/sol.jpg";

const Homepage = () => {
	return (
		<div className="homepage">
			<div className="panel-1">
				<div className="p1-heading-text">
					<div className="life-under-water">
						LIFE BELOW <div style={{ fontSize: "5vw" }}>WATER</div>
					</div>
					<div className="intro-text">
						<div className="introtexthead">
							Sustainable Development Goal 14
						</div>
						<div className="intotextbody">
							Conserve and sustainably use the oceans, seas and
							marine resources for sustainable development
						</div>
					</div>
				</div>
			</div>
			<div className="pc">
				<div className="InfoTile">
					<div className="InfotileHeadding"> THE PROBLEM</div>
					<div className="InfoTileContent">
						<p>
							Oceans are our planet’s life support and regulate
							the global climate system. More than three billion
							people depending on the oceans as their primary
							source of protein. Decades of irresponsible
							exploitation have led to an alarming level of
							degradation of such an important resource.{" "}
						</p>
						<p>
							The ocean absorbs around 23 per cent of annual CO2
							emissions generated by human activity and helps
							mitigate the impacts of climate change. The ocean
							has also absorbed more than 90% of the excess heat
							in the climate system. Ocean heat is at record
							levels, causing widespread marine heat waves,
							threatening its rich ecosystems and killing coral
							reefs around the world.
						</p>
						<p>
							Increasing levels of debris in the world’s oceans
							are also having a major environmental and economic
							impact. Every year, an estimated 5 to 12 million
							metric tonnes of plastic enters the ocean. About 89%
							of plastic litter found on the ocean floor are
							single-use items like plastic bags. About 80% of all
							tourism takes place in coastal areas. Unless
							carefully managed, tourism can pose a major threat
							to the natural resources on which it depends, and to
							local culture and industry.
						</p>
					</div>
				</div>
				<img src={Sharky} alt="broken" className="timage" />
			</div>
			<div className="pc">
				<img src={Trash} alt="broken" className="timage" />
				<div className="InfoTile">
					<div className="InfotileHeadding"> THE GRAVITY</div>
					<div className="InfoTileContent">
						<p>
							Well, without the oceans, the world loses 97% of its
							water. The small amount of liquid left wouldn’t be
							enough to sustain the water cycle. The pools of
							drinkable water would evaporate pretty fast. In a
							matter of days, people and most animals would die
							from dehydration. Without ocean waters, there will
							be no marine life that will survive. The world’s
							oceans – their temperature, chemistry, currents and
							life – drive global systems that make the Earth
							habitable for humankind. Our rainwater, drinking
							water, weather, climate, coastlines, much of our
							food, and even the oxygen in the air we breathe, are
							all ultimately provided and regulated by the sea.
							Throughout history, oceans and seas have been vital
							conduits for trade and transportation.
						</p>
					</div>
				</div>
			</div>
			<div className="pc">
				<div className="InfoTile">
					<div className="InfotileHeadding">THE SOLUTION</div>
					<div className="InfoTileContent">
						<p>
							For open oceans and deep sea areas, sustainability
							can be achieved only through increased international
							cooperation to protect vulnerable habitats.
							Establishing comprehensive, effective and equitably
							managed systems of government-protected areas should
							be pursued to conserve biodiversity and ensure a
							sustainable future for the fishing industry. On a
							local level, we should make ocean-friendly choices
							when buying products or eating food derived from
							oceans and consume only what we need. Selecting
							certified products is a good place to start. We
							should eliminate plastic usage as much as possible
							and organize beach clean-ups. Most importantly, we
							can spread the message about how important marine
							life is and why we need to protect it.
						</p>
						<p>
							The oceans of the Earth can exist without us. If we
							humans become extinct, they won’t even notice we’re
							gone. We, however, simply cannot exist without our
							oceans. We need them. So, whether we save them or
							not depends on what ‘we’ do.
						</p>
					</div>
				</div>
				<img src={Sol} alt="broken" className="timage" />
			</div>
			<p>
				Delevoped by Sai Vishal, Sai Supreeth, Sai Ganesh, Rushi Bhargav
				- IT Second year
			</p>
		</div>
	);
};

export default Homepage;
